name: Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu al
        uses: actions/checkout@v4

      - name: GHCR girisi
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker image build ve push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/ibrahimzengintechlife/iz-docker-app:latest
       deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH ile sunucuya deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: sudo /opt/deploy/iz-docker-app-deploy.sh
